### ISSUE TITLE
Can not create a model by running this in DartEditor

### ISSUE THREAD

**Issue by ride4sun** [dzenanr/model_concepts#1]
Thx for creating this tool. I am trying to use it based on the book chapter. I just forked the code and run it in DartEditor. The tool shows up in Chromium(http://localhost:8080/model_concepts.html) 
But I can not create a new class type or anything in the Canvas. You description said: 
"Click the concept tool in the tool bar (brown background) to create a concept by clicking on an empty space in the model"

I did that and many other things but I don't see any boxes showing up representing classes.
Any idea ... must be something trivial.
Thx, Joerg

**Comment by dzenanr** [comment]
There are 3 tools: select (arrow), relationship (line) and concept
(rectangle).

If you double-click on the concept tool it will stay active. Each click on
an empty space in the canvas will create a new concept. You can name the
last concept by entering its name in the Concept field.

> If you click only once on the concept tool, you will be able to create a
> new concept, but the active tool will become the select (arrow) tool. If
> you select the concept you will be able to change its title and add
> attributes.

Dzenan
http://learningdart.org/

**Comment by dzenanr** [comment]
The active tool will change its border.

Dzenan
http://learningdart.org/

**Comment by ride4sun** [comment]
Hello Dzenan,

Well I clicked the Square and than the Canvas – nothing.

Doubleclicked and than the Canvas – nothing.

Is that a supported method to get the code from git and than run it
directly from the DartEditor?

Thx for the help, Joerg

**Comment by ride4sun** [comment]
Here is a short video what I did....
https://onedrive.live.com/redir?resid=5BC80ECDD80B39BE!24713&authkey=!AK7sw5r8pUG7Ck0&ithint=video%2cmp4

**Comment by dzenanr** [comment]
You can run Model Concepts from Dart Editor or you can generate JavaScript
and use it in any browser. I have hundreds of students and this is the
first time that I hear about such a problem. If you have time today I can
show you over a Google hangout how to use Model Concepts.

Dzenan
http://learningdart.org/

**Comment by ride4sun** [comment]
Hello Dzenan, thx for you offer to help me over hangout. You can contact me on hangout any time. I have no video or audio(over my pc) here at work but I could call you and share my screen over hangout. 
Otherwise tomorrow I work from home and I we can use all of the above.

**Comment by dzenanr** [comment]
OK then tomorrow. I am in Quebec City (New York time). It is now 12:15 PM.

You should add me on your Google+ so that we can use a hangout easily.

Dzenan
http://learningdart.org/

**Comment by ride4sun** [comment]
Great I added u. Just ping me. Any time is fine during the day.
I am in California.

Thx, Joerg

**Comment by dzenanr** [comment]
Is ride4sun your Google+ name?

Dzenan
http://learningdart.org/

**Comment by dzenanr** [comment]
Do you have Chrome browser on your computer?

Canvas is a part of HTML5 and IE does not support well HTML5

I gave up on Microsoft long time ago.

Dzenan
http://learningdart.org/

**Comment by dzenanr** [comment]
Or use Dart Editor and run Model Concepts in Dartium (Dartium = Chromium +
Dart VM; part of Dart Editor).

select model_concepts.html
right button -> Run in Dartium

Dzenan
http://learningdart.org/

**Comment by dzenanr** [comment]
https://html5test.com/results/desktop.html

Dzenan
http://learningdart.org/

**Comment by ride4sun** [comment]
I did that - same problem. I run Chrome or Chromium.
I got 511 in the HTML 5 score and I don't use Explorer
Joerg

**Comment by ride4sun** [comment]
Well I just tried to run it as Javascript in Chrome and that worked.
I am online in Hangout if you have a few minutes.
Thx, Joerg

**Comment by dzenanr** [comment]
OK. Will you start a hangout?

Dzenan
http://learningdart.org/

**Comment by dzenanr** [comment]
I do not have your complete Google+ name. Thus, I cannot invite you for a
hangout. My Google+ name is my name: Dzenan Ridjanovic

Dzenan
http://learningdart.org/

**Comment by ride4sun** [comment]
I am on Hangout. My Hangout name is ride4sun
